using Proyecto;
VehiculoBase carro1 = new VehiculoBase();
PickUp one = new PickUp();
Sedan two=new Sedan();
SUV three=new SUV();
_4x4 four=new _4x4();
//propiedades de la base
carro1.Marca = "Toyota";
carro1.Modelo = "Prius";
carro1.Color = "Negro";
carro1.Anio = 2004;
carro1.Placa = "P735SÑQ";
carro1.Tipo = "Mecanico";
//propiedades del pick up
one.Marca = "Toyota";
one.Modelo = "Hilux";
one.Color = "Azul";
one.Anio = 2021;
one.Placa = "P844KSF";
one.Tipo = "Automatico";
one.Llantas = "4x4";
one.Motor = "Electrico";
one.Radio = "Musica: Bohemian rhapsody";
//propiedades del sedan
two.Marca = "Mitsubishi";
two.Modelo = "Mirage G4";
two.Color = "Gris";
two.Anio = 2017;
two.Placa = "P001SPQ";
two.Tipo = "Mecanico";
two.Gabinete = "Trae gabinete";
two.Sillones = "Trae 5 asientos";
two.Aceite = "Trae aceite";
//propiedades del suv
three.Marca = "Skoda";
three.Modelo = "Kamiq";
three.Color = "Rojo";
three.Anio = 2020;
three.Placa = "P299YJA";
three.Tipo = "Mecanico";
three.Pequeño = "Es un auto pequeño";
three.Seguro = "Es un auto seguro";
three.Economico = "Es un auto economico";
//propiedades del 4x4
four.Marca = "Mitsubishi";
four.Modelo = "L200";
four.Color = "Blanco";
four.Anio = 2019;
four.Placa = "P901ZDM";
four.Tipo = "Automatico";
four.Hermoso = "Es un auto hermoso";
four.Comodo = "Es un auto comodo";
four.Caro = "Es un auto caro";
//consola base
Console.WriteLine("----------------------------");
Console.WriteLine(carro1.Marca);
Console.WriteLine(carro1.Modelo);
Console.WriteLine(carro1.Color);
Console.WriteLine(carro1.Anio);
Console.WriteLine(carro1.Placa);
Console.WriteLine(carro1.Tipo);
Console.WriteLine("----------------------------");
carro1.Encender();
carro1.Bocina();
carro1.Acelerar(21);
carro1.nose(21, 120);
carro1.Frenar(5);
carro1.Apagar();
//consola pick up
Console.WriteLine("----------------------------");
Console.WriteLine(one.Marca);
Console.WriteLine(one.Modelo);
Console.WriteLine(one.Color);
Console.WriteLine(one.Anio);
Console.WriteLine(one.Placa);
Console.WriteLine(one.Tipo);
Console.WriteLine(one.Llantas);
Console.WriteLine(one.Motor);
Console.WriteLine(one.Radio);
Console.WriteLine("----------------------------");
one.Encender1();
one.Abrirventa();
one.Apagar();
//consola sedan
Console.WriteLine("----------------------------");
Console.WriteLine(two.Marca);
Console.WriteLine(two.Modelo);
Console.WriteLine(two.Color);
Console.WriteLine(two.Anio);
Console.WriteLine(two.Placa);
Console.WriteLine(two.Tipo);
Console.WriteLine(two.Gabinete);
Console.WriteLine(two.Sillones);
Console.WriteLine(two.Aceite);
Console.WriteLine("----------------------------");
two.EncenderSedan();
two.Abrirbaul();
two.Cerrarbaul();
//consola suv
Console.WriteLine("----------------------------");
Console.WriteLine(three.Marca);
Console.WriteLine(three.Modelo);
Console.WriteLine(three.Color);
Console.WriteLine(three.Anio);
Console.WriteLine(three.Placa);
Console.WriteLine(three.Tipo);
Console.WriteLine(three.Pequeño);
Console.WriteLine(three.Seguro);
Console.WriteLine(three.Economico);
Console.WriteLine("----------------------------");
three.EncenderSUV();
three.Abrircapo();
//consola 4x4
Console.WriteLine("----------------------------");
Console.WriteLine(four.Marca);
Console.WriteLine(four.Modelo);
Console.WriteLine(four.Color);
Console.WriteLine(four.Anio);
Console.WriteLine(four.Placa);
Console.WriteLine(four.Tipo);
Console.WriteLine(four.Hermoso);
Console.WriteLine(four.Comodo);
Console.WriteLine(four.Caro);
Console.WriteLine("----------------------------");
four.Encender4x4();
four.Luces();
Console.WriteLine("----------------------------");